CREATE TABLE amarillo(
idObjeto TINYINT(1) AUTO_INCREMENT,
nombre VARCHAR(20) NOT NULL,
url VARCHAR(40) NOT NULL,
PRIMARY KEY (idObjeto)
    
)
CREATE TABLE azul(
idObjeto TINYINT(1) AUTO_INCREMENT,
nombre VARCHAR(20) NOT NULL,
url VARCHAR(40) NOT NULL,
PRIMARY KEY (idObjeto)
    
)
CREATE TABLE verde(
idObjeto TINYINT(1) AUTO_INCREMENT,
nombre VARCHAR(20) NOT NULL,
url VARCHAR(40) NOT NULL,
PRIMARY KEY (idObjeto)
    
)